[features]
seeds = false
skip-lint = false

[programs.localnet]
move_token = "EwXc7JJzABwkFUf1ZuxD72gh4BU3YttzGxos29n469TU"
simple_liquidity_pool = "5X1W5dFYoDhBN24iS2t8vwDUR6y5wvDdfxT3gwG6P4hA"

[programs.devnet]
move_token = "EwXc7JJzABwkFUf1ZuxD72gh4BU3YttzGxos29n469TU"
simple_liquidity_pool = "5X1W5dFYoDhBN24iS2t8vwDUR6y5wvDdfxT3gwG6P4hA"

[programs.testnet]
move_token = "EwXc7JJzABwkFUf1ZuxD72gh4BU3YttzGxos29n469TU"
simple_liquidity_pool = "5X1W5dFYoDhBN24iS2t8vwDUR6y5wvDdfxT3gwG6P4hA"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Localnet"
cluster = "devnet"
#cluster = "testnet"
wallet = "/Users/macos/.config/solana/id.json"

[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 programs/**/lib.test.ts"
#-- test a single program, read README.md for more detail
#-- Eg:
test-program="yarn test-program"
#-- test a single test file, or any matching pattern, read README.md for more detail
#-- Eg: anchor run test-only -- tests/tmp/tmp.ts
test-only = "yarn test-only"
